######################################################################
# $Id: Makefile,v 1.14 2001/11/02 23:13:03 seth Exp $
#
# ++Copyright LIBBK++
#
# Copyright (c) 2001 The Authors.  All rights reserved.
#
# This source code is licensed to you under the terms of the file
# LICENSE.TXT in this release for further details.
#
# Mail <projectbaka@baka.org> for further information
#
# --Copyright LIBBK--
#
# libbk Makefile
#
BK_LARGE_LIB=libbk.a

BK_LARGE_LIBSRC=		       		\
		b_bits.c			\
		b_cksum.c			\
		b_debug.c			\
		b_config.c			\
		b_error.c			\
		b_fun.c 			\
		b_funlist.c			\
		b_general.c			\
		b_ioh.c				\
		b_memx.c			\
		b_run.c				\
		b_stdfun.c			\
		b_string.c			\
# Line eater fodder -- leave

GROUPTOP=..
GROUPSUBDIR=lib
##################################################
## BEGIN BKSTANDARD MAKEFILE
-include ./Make.preinclude
-include $(GROUPTOP)/Make.preinclude
-include $(GROUPTOP)/$(PKGTOP)/Make.preinclude
include $(GROUPTOP)/$(PKGTOP)/bkmk/Make.include
-include $(GROUPTOP)/$(PKGTOP)/Make.include
-include $(GROUPTOP)/Make.include
-include ./Make.include
## END BKSTANDARD MAKEFILE
##################################################
